section 1 of 63C
openid-foundation-japan/800-63-4-draft pull request #1
Opened 2022-12-21 10:48 UTC by nov

2022-12-21 10:51 UTC, nov commented
testing slack integration

2022-12-21 10:53 UTC, nov commented
testing slack integration

2022-12-21 10:54 UTC, nov commented
testing slack integration

2022-12-21 10:55 UTC, nov commented
testing slack integration

2022-12-21 10:56 UTC, nov commented
testing slack integration

2023-02-03 02:18 UTC, kurumai requested changes

2023-02-03 02:18 UTC, kurumai commented on _sp800-63c/sec10_usability.ja.md
> +Federation は多くのユーザーにとってあまり馴染みのないユーザーインタラクションの形態であるため, これは特に Federated Identity Systemに当てはまることである.
```suggestion
Federation は多くのユーザーにとってあまり馴染みのないユーザーインタラクションの形態であるため, これは特に Federated Identity System に当てはまることである.
```

2023-02-03 02:18 UTC, kurumai commented on _sp800-63c/sec10_usability.ja.md
> +Federated Identity Systemにおける全体のユーザーエクスペリエンスは可能な限りスムースかつ容易であるべきである.
```suggestion
Federated Identity System における全体のユーザーエクスペリエンスは可能な限りスムースかつ容易であるべきである.
```

2023-02-03 02:18 UTC, kurumai commented on _sp800-63c/sec10_usability.ja.md
> +Usability とは異なり, アクセスビリティに関しては本書のスコープ外とする.
```suggestion
Usability とは異なり, アクセシビリティに関しては本書のスコープ外とする.
```

2023-02-03 02:18 UTC, kurumai commented on _sp800-63c/sec10_usability.ja.md
> +アクセスビリティガイドラインに関しては Section 508 の法律および標準を参照のこと.
```suggestion
アクセシビリティガイドラインに関しては Section 508 の法律および標準を参照のこと.
```

2023-02-03 02:18 UTC, kurumai commented on _sp800-63c/sec10_usability.ja.md
> +* 技術的な支援を受ける方法とその場所を明確に伝えること. 例えばオンラインのせフルサービス機能へのリンク, チャット, ヘルプデスクサポートの電話番号などを提供することなどが考えられる. ユーザーが技術的な支援を受けるために関与する当事者間 (e.g., RP, IdP および Broker) をたらい回しにされる事態は避けること.
```suggestion
* 技術的な支援を受ける方法とその場所を明確に伝えること. 例えばオンラインのセルフサービス機能へのリンク, チャット, ヘルプデスクサポートの電話番号などを提供することなどが考えられる. ユーザーが技術的な支援を受けるために関与する当事者間 (e.g., RP, IdP および Broker) をたらい回しにされる事態は避けること.
```

2023-02-03 02:18 UTC, kurumai commented on _sp800-63c/sec10_usability.ja.md
> +* 適切なコンテキストにおける代表的なユーザーと現実的なタスクを前提に, 統合的かつ継続的な Usalibity 評価を実施し, ユーザーの観点から Federated Identity Systemの成功を保証すること.
```suggestion
* 適切なコンテキストにおける代表的なユーザーと現実的なタスクを前提に, 統合的かつ継続的な Usalibity 評価を実施し, ユーザーの観点から Federated Identity System の成功を保証すること.
```

2023-02-03 02:18 UTC, kurumai commented on _sp800-63c/sec10_usability.ja.md
> +* ユーザーに, 一意で意味のあるわかりやすい識別子を提供し, IdP, RP, Account などの主体を区別できるようにする. ユーザーが目にする識別子は, その下で動くプロトコル内で使用される通常ユーザーの目に触れることのない識別子に加え, 使用される可能性がある.
```suggestion
* ユーザーに, 一意で意味のあるわかりやすい識別子を提供し, IdP, RP, Account などの主体を区別できるようにする. ユーザーが目にする識別子は, その下で動くプロトコル内で使用される通常ユーザーの目に触れることのない識別子に加えて使用される可能性がある.
```

2023-02-03 02:18 UTC, kurumai commented on _sp800-63c/sec10_usability.ja.md
> +* ユーザーに, データを更新するすべを提供する. 関連する主体がもはや存在しない場合においても.
```suggestion
* 関連する主体がもはや存在しない場合においても, ユーザーにデータを更新するすべを提供する. 
```

2023-02-03 02:18 UTC, kurumai commented on _sp800-63c/sec10_usability.ja.md
> +* ユーザーに, 自信の Identity を完全に削除たり, 自身に関する情報を全て削除したりするすべを提供する. これには Transaction 履歴も含む. なお, このようなアクションを妨げる可能性のある監査, 法律ないしポリシー上の制約がないか考慮すること. 場合によっては削除よりも完全な非アクティブ化が適切である.
```suggestion
* ユーザーに, 自身の Identity を完全に削除したり, 自身に関する情報を全て削除したりするすべを提供する. これには Transaction 履歴も含む. なお, このようなアクションを妨げる可能性のある監査, 法律ないしポリシー上の制約がないか考慮すること. 場合によっては削除よりも完全な非アクティブ化が適切である.
```

2023-02-03 02:18 UTC, kurumai commented on _sp800-63c/sec10_usability.ja.md
> +* ユーザーに, 組織のデータアクセスポリシーに従って, 適切な匿名性および仮名性のオプション, および必要に応じてそのような Identity オプションを切り替えるすべを提供する.
```suggestion
* ユーザーに, 組織のデータアクセスポリシーに従って, 適切な匿名性および Pseudonymity のオプション, および必要に応じてそのような Identity オプションを切り替えるすべを提供する.
```

2023-02-03 02:18 UTC, kurumai commented on _sp800-63c/sec10_usability.ja.md
> +最後に, プジティブなユーザーエクスペリエンスは Federation に対するユーザーの要求を増大させ, RP による採用増加も引き起こす可能性がある.
```suggestion
最後に, ポジティブなユーザーエクスペリエンスは Federation に対するユーザーの要求を増大させ, RP による採用増加も引き起こす可能性がある.
```

2023-02-05 00:44 UTC, kurumai requested changes

2023-02-05 00:44 UTC, kurumai commented on _sp800-63c/sec11_equity.ja.md
> +はこれを定めている.
```suggestion
```

2023-02-05 00:44 UTC, kurumai commented on _sp800-63c/sec11_equity.ja.md
> +* 田舎に住んでいるなど, 信頼できる Network 接続を持たない Subscriber にとっては, タイムアウトせずに全体の Federated Transaction を完了させるのは困難かもしれない.
```suggestion
* 地方に住んでいるなど, 信頼できる Network 接続を持たない Subscriber にとっては, タイムアウトせずに全体の Federated Transaction を完了させるのは困難かもしれない.
```

2023-02-05 00:44 UTC, kurumai commented on _sp800-63c/sec11_equity.ja.md
> +RP はそのような Subscriber に対してローカルで認証された Account を作成し, 後でそれらの Account を Federated Identifier に紐づけることを可能にすることもできる.
```suggestion
RP はそのような Subscriber に対してローカルで Authenticate された Account を作成し, 後でそれらの Account を Federated Identifier に紐づけることを可能にすることもできる.
```

2023-02-05 00:44 UTC, kurumai commented on _sp800-63c/sec12_examples.ja.md
> +ただし, Password ベースの Kerberos Authentication が FAST (または類似の) トンネル内で用いられている場合, 自書攻撃を実行するには中間者攻撃を成功させることも必要になる.
```suggestion
ただし, Password ベースの Kerberos Authentication が FAST (または類似の) トンネル内で用いられている場合, 辞書攻撃を実行するには中間者攻撃を成功させることも必要になる.
```

2023-02-05 00:44 UTC, kurumai commented on _sp800-63c/sec1_purpose.ja.md
> +本ドキュメント SP 800-63C は Federated Identity System における Identity Provider (IdPs) および Relying Party (RP) に対する要件を定める.
```suggestion
本ドキュメント SP 800-63C は Federated Identity System における Identity Provider (IdP) および Relying Party (RP) に対する要件を定める.
```

2023-02-05 06:40 UTC, kurumai requested changes

2023-02-05 06:40 UTC, kurumai commented on _sp800-63c/sec2_introduction.ja.md
> +これらの Attribute Value や Derived Attribute Value はしばしば Attribute-based Access Control (ABAC) における Access 権限の決定やトランザクション (e.g., 配送先住所の提供) を促進するために用いられる.
```suggestion
これらの Attribute Value や Derived Attribute Value はしばしば Attribute-based Access Control (ABAC) における Access 権限の決定や Transaction の促進 (e.g., 配送先住所の提供) に用いられる.
```

2023-02-05 06:40 UTC, kurumai commented on _sp800-63c/sec4_fal.ja.md
> +各レベルは, それ以下のレベルの全要件を内包および満たす. (e.g., FAL3 で実施される Federation は FAL2 や FAL1 を満たすものとして許容可能である. FAL3 を満たしていれば, FAL2 や FAL1 の全ての要件を満たしている.)
```suggestion
各レベルは, それ以下のレベルの全要件を内包および満たす. (e.g., FAL3 は下位レベルの要件をすべて満たしているため, FAL3 を満たしていれば, FAL2 や FAL1 の全ての要件を満たしている.)
```

2023-02-05 06:40 UTC, kurumai commented on _sp800-63c/sec4_fal.ja.md
> +FAL1 における Assertion は全て, 特定の RP (群) に対する Audience Restriction が施されなければならず (**SHALL**), RP が当該 Assertion の Audience に自身が含まれていることを確認せねばならない.
```suggestion
FAL1 における Assertion は全て, 特定の RP (群) に対する Audience Restriction が施されなければならず (**SHALL**), RP が当該 Assertion の Audience に自身が含まれていることを確認せねばならない (**SHALL**).
```

2023-02-05 06:40 UTC, kurumai commented on _sp800-63c/sec4_fal.ja.md
> +IdP は, HTTPS で保護された well-known location を用いるなど, 検証可能な形で自身の Public Key を公開してもよい.
```suggestion
IdP は, HTTPS で保護された well-known location を用いるなど, 検証可能な形で自身の Public Key を公開してもよい (**MAY**).
```

2023-02-05 06:40 UTC, kurumai commented on _sp800-63c/sec4_fal.ja.md
> +FAL3 ではm Subscriber は Assertion に加えて Authenticator を Direct に RP に提示することで Authenticate せねばならない (**SHALL**).
```suggestion
FAL3 では Subscriber は Assertion に加えて Authenticator を Direct に RP に提示することで Authenticate せねばならない (**SHALL**).
```

2023-02-05 06:40 UTC, kurumai commented on _sp800-63c/sec4_fal.ja.md
> +FAL3 では, IdP-RP 間の Trust Agreement および Registrationは Static に確立されなければならない (**SHALL**).
```suggestion
FAL3 では, IdP-RP 間の Trust Agreement および Registration は Static に確立されなければならない (**SHALL**).
```

2023-02-05 19:39 UTC, kurumai requested changes

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec5_federation.ja.md
> +この場合, RP は Subscriber に対して IdP に対して当該 RP が要求する全 Attribute の利用について通知し, IdP はそれらの Attribute の開示について Subscriber に同意を促す.
```suggestion
この場合, RP は IdP に対して当該 RP が要求する全 Attribute の利用について Subscriber に通知し, IdP はそれらの Attribute の開示について Subscriber に同意を促す.
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec5_federation.ja.md
> +RP は IdP から提示されたこの Assertion を処理し, Subscriber との間に認証済 Session を確立する.
```suggestion
RP は IdP から提示されたこの Assertion を処理し, Subscriber との間に Authenticate 済みの Session を確立する.
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec5_federation.ja.md
> +IdP は自信がサポートする IAL, AAL および FAL を RP に開示せねばならない (**SHAL**).
```suggestion
IdP は自信がサポートする IAL, AAL および FAL を RP に開示せねばならない (**SHALL**).
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec5_federation.ja.md
> +Federation Authority は, 自信が有効にする Federation 関係に対して, 期待される許容可能な IAL, AAL および FAL に関するパラメータを確立しなければならない (**SHALL**).
```suggestion
Federation Authority は, 自身が有効にする Federation 関係に対して, 期待される許容可能な IAL, AAL および FAL に関するパラメータを確立しなければならない (**SHALL**).
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec5_federation.ja.md
> +IdP と RP の審査結果は最低限以下のようなものとなる.
```suggestion
IdP と RP の審査結果は最低限以下のようなものとなる (**SHALL**).
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec5_federation.ja.md
> +これらの全ての情報は, Federation Protocol のん範囲ないで IdP と RP がデジタルかつプログラム的に信頼を確立するために用いられる.
```suggestion
これらの全ての情報は, Federation Protocol の範囲内で IdP と RP がデジタルかつプログラム的に信頼を確立するために用いられる.
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec5_federation.ja.md
> +このプロセスは, システム管理者や開発者が情報を大正システムに入力するといった形で手動 (Manual) かつ Static に行われることもあるし, 人間の直接的関与なしにシステム自身が情報を交換する形で自動的かつ Dynamic に行われることもある.
```suggestion
このプロセスは, システム管理者や開発者が情報を対象システムに入力するといった形で手動 (Manual) かつ Static に行われることもあるし, 人間の直接的関与なしにシステム自身が情報を交換する形で自動的かつ Dynamic に行われることもある.
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec5_federation.ja.md
> +Static Trust Agreement において, IdP は RP の Allowhist をもうけ, そこに含まれる RP については当該 IdP から Subscriber による実行時決定無しに Authentication および Attribute を受け取ることを認可されたものとすることができる (**MAY**).
```suggestion
Static Trust Agreement において, IdP は RP の Allowlist をもうけ, そこに含まれる RP については当該 IdP から Subscriber による実行時決定無しに Authentication および Attribute を受け取ることを認可されたものとすることができる (**MAY**).
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec5_federation.ja.md
> +このプロセスにより, RP は識別子が示す適切な IdP をプログラム的に IdP を選択できるようになる.
```suggestion
このプロセスにより, RP は識別子が示す適切な IdP をプログラム的に選択できるようになる.
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec5_federation.ja.md
> +このメカニズムは RP における Authentication の前に用いられるため, RP がこのメカニズムを提供する方法 (認証済 Session 外のブラウザクッキー等) は [Sec. 5.4](sec5_federation.ja.md#rp-account) に述べる RP Subscriber Account とは紐づかない.
```suggestion
このメカニズムは RP における Authentication の前に用いられるため, RP がこのメカニズムを提供する方法 ( Authenticate 済みの Session 外のブラウザクッキー等) は [Sec. 5.4](sec5_federation.ja.md#rp-account) に述べる RP Subscriber Account とは紐づかない.
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec7_presentation.ja.md
> +Assertion は, [Sec. 5.1.3](sec5_federation.ja.mdmd#proxied) で述べたように, IdP-RP 間の Federation 促進のため, 上記とはまたの提示方法を用いて Proxy されることもある (**MAY**).
```suggestion
Assertion は, [Sec. 5.1.3](sec5_federation.ja.mdmd#proxied) で述べたように, IdP-RP 間の Federation 促進のため, 上記とはまた別の提示方法を用いて Proxy されることもある (**MAY**).
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec7_presentation.ja.md
> +この手法では, RP が IdP に対して Assertion 自体には含まれていない Subscriber の追加の Attribute を照会すること促進する.
```suggestion
この手法では, RP が IdP に対して Assertion 自体には含まれていない Subscriber の追加の Attribute を照会することを促進する.
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec7_presentation.ja.md
> +IdP は, RP が IdP に Assertion Reference を提示際に Authentication を要求したり, その他の類似手段 (あるプロトコルにおける動的 RP 検証方法については [[RFC7636]](references.ja.md#ref-RFC7636) を参照) によりこれを実現できる.
```suggestion
IdP は, RP が IdP に Assertion Reference を提示する際に Authentication を要求したり, その他の類似手段 (あるプロトコルにおける動的 RP 検証方法については [[RFC7636]](references.ja.md#ref-RFC7636) を参照) によりこれを実現できる.
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec5_federation.ja.md
> +このようなインアクティブな Account を処理する際, RP は可能であれば保留中の Account の Terminate について Subscriber に十分な通知をおこなうこととし, スケジュールされた Terminate の前に Subscriber に Account を再アクティベイトするオプションを提供することとする (**SHALL**).
```suggestion
このようなインアクティブな Account を処理する際, RP は可能であれば保留中の Account の Terminate について Subscriber に十分な通知を行うこととし, スケジュールされた Terminate の前に Subscriber に Account を再アクティベイトするオプションを提供することとする (**SHALL**).
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec5_federation.ja.md
> +IdP から RP への Signaling には Static Trust Agreement が必要となる.
```suggestion
IdP から RP への Signaling には Static Trust Agreement が必要となる (**SHALL**).
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec5_federation.ja.md
> +RP から IdP への Signaling には Static Trust Agreement ないしは Dynamic Trust Agreement が必要となる.
```suggestion
RP から IdP への Signaling には Static Trust Agreement ないしは Dynamic Trust Agreement が必要となる (**MAY**).
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec6_assertions.ja.md
> +2. Attribute Metadata: Subscriber Attribute に関する1つ以上の追加情報. NIST Internal Report 8112 [[NISTIR8112]](references.ja.md#ref-nistir8112) 例示あり.
```suggestion
2. Attribute Metadata: 1つ以上の Subscriber Attribute に関する追加情報. NIST Internal Report 8112 [[NISTIR8112]](references.ja.md#ref-nistir8112) 例示あり.
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec6_assertions.ja.md
> +例としては RP の識別や Assertion インジェクションにたいする保護策などが考えられる.
```suggestion
例としては RP の識別や Assertion インジェクションに対する保護策などが考えられる.
```

2023-02-05 19:39 UTC, kurumai commented on _sp800-63c/sec6_assertions.ja.md
> +RP が Boud Authenticator とともに Assertion を受け取る際, Subscriber は RP に直接 Bound Authenticator の保持証明を行う.
```suggestion
RP が Bound Authenticator とともに Assertion を受け取る際, Subscriber は RP に直接 Bound Authenticator の保持証明を行う.
```

2023-02-05 19:58 UTC, kurumai requested changes

2023-02-05 19:58 UTC, kurumai commented on _sp800-63c/sec9_privacy.ja.md
> +Subscriber の同意は意味のあるのでなければならず, IdP が同意による手段をとる場合は, Subscriber による追加利用に関する同意を Identity Servicee の提供条件にしてはならない.
```suggestion
Subscriber の同意は意味のあるものでなければならず, IdP が同意による手段をとる場合は, Subscriber による追加利用に関する同意を Identity Servicee の提供条件にしてはならない.
```

2023-02-05 19:58 UTC, kurumai commented on _sp800-63c/sec9_privacy.ja.md
> +[Sec. 5.5](sec5_federation.md#privacy-reqs) では, Disassociability (システム運用上の要件を超えて個人またはデバイスに関連付けることなく, PII またはイベントの処理を可能にすること) を提供する技術的手段の採用も推奨しており, Subscriber のアクティビティがトラキングされたりプロファイリングされることを防止している [[
```suggestion
[Sec. 5.5](sec5_federation.md#privacy-reqs) では, Disassociability (システム運用上の要件を超えて個人またはデバイスに関連付けることなく, PII またはイベントの処理を可能にすること) を提供する技術的手段の採用も推奨しており, Subscriber のアクティビティがトラッキングされたりプロファイリングされることを防止している [[NISTIR8062]](references.md#ref-NISTIR8062).
```

2023-02-05 19:58 UTC, kurumai commented on _sp800-63c/sec9_privacy.ja.md
> +[Sec. 6.2.5](sec6_assertions.md#ppi) で述べた Proxied Federation や [Sec. 6.2.5](sec6_assertions.md#ppi) で述べた Pairwise Pseudonymous Identifier  [Sec. 5.1.3](sec5_federation.md#proxied) のような技術的手段は, Subscri
```suggestion
[Sec. 6.2.5](sec6_assertions.md#ppi) で述べた Proxied Federation や [Sec. 6.2.5](sec6_assertions.md#ppi) で述べた Pairwise Pseudonymous Identifier  [Sec. 5.1.3](sec5_federation.md#proxied) のような技術的手段は, Subscriber を運用上の要件を超えてトラッキングないしプロファイリングすることをより困難にし, ポリシー適用の効率化に寄与しうる.
```

2023-02-06 04:26 UTC, nov commented on _sp800-63c/sec5_federation.ja.md
> +このメカニズムは RP における Authentication の前に用いられるため, RP がこのメカニズムを提供する方法 (認証済 Session 外のブラウザクッキー等) は [Sec. 5.4](sec5_federation.ja.md#rp-account) に述べる RP Subscriber Account とは紐づかない.
"Authenticated Session" に統一しようと思います。

2023-02-06 04:26 UTC, merged